### ISSUE TITLE
LoadffmpegBinary issue

### ISSUE THREAD

**Issue by Dinesh651** [bhuvnesh123/FFmpeg-Video-Editor-Android#38]
after calling method "LoadffmpeBinary" my text layout of whole app got changed from center to left alignment,

**Comment by bhuvnesh123** [comment]
@Dinesh651 I am NOT doing any UI change inside loadFFMpegBinary().So alignment change can't be due to calling method loadFFMpegBinary().Please recheck your code and if the issue persists share with me your layout xml file along with its associated java/kotlin code at bhuvneshvarma123@gmail.com so that I can help you with your code!
